# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7ec22b4d50a79a64b5ba212121b1d956e3e2aac73dde6fe1be2cfc8a32b94da486962a36f030b8b1b834b4a89d099634b7608292995e4c9afcedbb1b062239

test:
  secret_key_base: c02f1e3a0a83ee0b0001f81b2546ec2228943b24fca6a320a9262f7daf5fd009a53a0f2870c879e7a8e243386e95e5219e2fcdb7f12946cf0ca1c14c97025b45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
